name: Build and push image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo-test-jib

    steps:
      - uses: actions/checkout@v3

      - name: install jdk 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: build with maven
        run: ./mvnw verify

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        run: ./mvnw clean package -DskipTests